export const HendrixEdwardBillyTxData = [
  {
    txName: "Apparel Production Inc.",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jun 04, 2022",
    color: "green",
  },
  {
    txName: "Call To Action Clothing",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 25, 2022",
    color: "green",
  },
  {
    txName: "Etfashion",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 19, 2022",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "Jun 04, 2022",
    color: "red",
  },
  {
    txName: "Gebbers Farms",
    whatUsed: "Credit",
    debit: "+$500,000.00",
    date: "May 05, 2022",
    color: "green",
  },
  {
    txName: "Busch Agricultural Resources",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$400,000.00",
    date: "Apr 25, 2022",
    color: "red",
  },
  {
    txName: "Farm.One",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2022",
    color: "green",
  },
  {
    txName: "IJH FARM",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Jan 15, 2022",
    color: "red",
  },
  {
    txName: "Summit Agricultural Group",
    whatUsed: "Credit",
    debit: "+$135,000.00",
    date: "Jan 1, 2022",
    color: "green",
  },
  {
    txName: "Follow Suit Swimwear",
    whatUsed: "credit",
    debit: "+$195,000.00",
    date: "Dec 29, 2022",
    color: "green",
  },
  {
    txName: "Brunt Workwear",
    whatUsed: "credit",
    debit: "+$92,280.00",
    date: "Dec 21, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$237,350.00",
    date: "Dec 18, 2022",
    color: "red",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$40,000.00",
    date: "Dec 16, 2022",
    color: "red",
  },
  {
    txName: "Prestage Farms of Iowa",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Dec 08, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Dec 04, 2022",
    color: "red",
  },
];

export const KathleenWilsonTxData = [
  {
    txName: "Apparel Production Inc.",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jun 04, 2022",
    color: "green",
  },
  {
    txName: "Call To Action Clothing",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 25, 2022",
    color: "green",
  },
  {
    txName: "Etfashion",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 19, 2022",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "Jun 04, 2022",
    color: "red",
  },
  {
    txName: "Gebbers Farms",
    whatUsed: "Credit",
    debit: "+$500,000.00",
    date: "May 05, 2022",
    color: "green",
  },
  {
    txName: "Busch Agricultural Resources",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$400,000.00",
    date: "Apr 25, 2022",
    color: "red",
  },
  {
    txName: "Farm.One",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2022",
    color: "green",
  },
  {
    txName: "IJH FARM",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Jan 15, 2022",
    color: "red",
  },
  {
    txName: "Summit Agricultural Group",
    whatUsed: "Credit",
    debit: "+$135,000.00",
    date: "Jan 1, 2022",
    color: "green",
  },
  {
    txName: "Follow Suit Swimwear",
    whatUsed: "credit",
    debit: "+$195,000.00",
    date: "Dec 29, 2022",
    color: "green",
  },
  {
    txName: "Brunt Workwear",
    whatUsed: "credit",
    debit: "+$92,280.00",
    date: "Dec 21, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$237,350.00",
    date: "Dec 18, 2022",
    color: "red",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$40,000.00",
    date: "Dec 16, 2022",
    color: "red",
  },
  {
    txName: "Prestage Farms of Iowa",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Dec 08, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Dec 04, 2022",
    color: "red",
  },
];
export const DavidHuntingtonTxData = [
  {
    txName: "Mavis wanckyz",
    whatUsed: "Credit",
    debit: "+$1,000,000.00",
    date: "Oct 04, 2022",
    color: "green",
  },
  {
    txName: "Apparel Production Inc.",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jun 04, 2022",
    color: "green",
  },
  {
    txName: "Call To Action Clothing",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 25, 2022",
    color: "green",
  },
  {
    txName: "Etfashion",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 19, 2022",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "Jun 04, 2022",
    color: "red",
  },
  {
    txName: "Gebbers Farms",
    whatUsed: "Credit",
    debit: "+$500,000.00",
    date: "May 05, 2022",
    color: "green",
  },
  {
    txName: "Busch Agricultural Resources",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$400,000.00",
    date: "Apr 25, 2022",
    color: "red",
  },
  {
    txName: "Farm.One",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2022",
    color: "green",
  },
  {
    txName: "IJH FARM",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Jan 15, 2022",
    color: "red",
  },
  {
    txName: "Summit Agricultural Group",
    whatUsed: "Credit",
    debit: "+$135,000.00",
    date: "Jan 1, 2022",
    color: "green",
  },
  {
    txName: "Follow Suit Swimwear",
    whatUsed: "credit",
    debit: "+$195,000.00",
    date: "Dec 29, 2022",
    color: "green",
  },
  {
    txName: "Brunt Workwear",
    whatUsed: "credit",
    debit: "+$92,280.00",
    date: "Dec 21, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$237,350.00",
    date: "Dec 18, 2022",
    color: "red",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$40,000.00",
    date: "Dec 16, 2022",
    color: "red",
  },
  {
    txName: "Prestage Farms of Iowa",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Dec 08, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Dec 04, 2022",
    color: "red",
  },
];
export const PaulMaccartneyTxData = [
  {
    txName: "Mavis wanckyz",
    whatUsed: "Credit",
    debit: "+$1,000,000.00",
    date: "Oct 04, 2022",
    color: "green",
  },
  {
    txName: "Apparel Production Inc.",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jun 04, 2022",
    color: "green",
  },
  {
    txName: "Call To Action Clothing",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 25, 2022",
    color: "green",
  },
  {
    txName: "Etfashion",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 19, 2022",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "Jun 04, 2022",
    color: "red",
  },
  {
    txName: "Gebbers Farms",
    whatUsed: "Credit",
    debit: "+$500,000.00",
    date: "May 05, 2022",
    color: "green",
  },
  {
    txName: "Busch Agricultural Resources",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$400,000.00",
    date: "Apr 25, 2022",
    color: "red",
  },
  {
    txName: "Farm.One",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2022",
    color: "green",
  },
  {
    txName: "IJH FARM",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Jan 15, 2022",
    color: "red",
  },
  {
    txName: "Summit Agricultural Group",
    whatUsed: "Credit",
    debit: "+$135,000.00",
    date: "Jan 1, 2022",
    color: "green",
  },
  {
    txName: "Follow Suit Swimwear",
    whatUsed: "credit",
    debit: "+$195,000.00",
    date: "Dec 29, 2022",
    color: "green",
  },
  {
    txName: "Brunt Workwear",
    whatUsed: "credit",
    debit: "+$92,280.00",
    date: "Dec 21, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$237,350.00",
    date: "Dec 18, 2022",
    color: "red",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$40,000.00",
    date: "Dec 16, 2022",
    color: "red",
  },
  {
    txName: "Prestage Farms of Iowa",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Dec 08, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Dec 04, 2022",
    color: "red",
  },
];
export const JessicaCummingsTxData = [
  {
    txName: "YouTube",
    whatUsed: "Credit",
    debit: "+$1,000,000.00",
    date: "Jan 04, 2022",
    color: "green",
  },
  {
    txName: "Apparel Production Inc.",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jun 01, 2022",
    color: "green",
  },
  {
    txName: "Call To Action Clothing",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 25, 2021",
    color: "green",
  },
  {
    txName: "Etfashion",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 19, 2021",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "Jun 04, 2021",
    color: "red",
  },
  {
    txName: "Gebbers Farms",
    whatUsed: "Credit",
    debit: "+$500,000.00",
    date: "Feb 20, 2021",
    color: "green",
  },
  {
    txName: "Busch Agricultural Resources",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "Aug 10, 2020",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$400,000.00",
    date: "Apr 25, 2020",
    color: "red",
  },
  {
    txName: "Farm.One",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2020",
    color: "green",
  },
  {
    txName: "IJH FARM",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2020",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Dec 15, 2019",
    color: "red",
  },
  {
    txName: "Summit Agricultural Group",
    whatUsed: "Credit",
    debit: "+$135,000.00",
    date: "Oct 1, 2019",
    color: "green",
  },
  {
    txName: "Follow Suit Swimwear",
    whatUsed: "credit",
    debit: "+$195,000.00",
    date: "March 29, 2019",
    color: "green",
  },
  {
    txName: "Brunt Workwear",
    whatUsed: "credit",
    debit: "+$92,280.00",
    date: "Dec 21, 2018",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$237,350.00",
    date: "Jan 18, 2018",
    color: "red",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$40,000.00",
    date: "Jan 03, 2018",
    color: "red",
  },
  {
    txName: "Prestage Farms of Iowa",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Dec 08, 2017",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "May 04, 2017",
    color: "red",
  },
];
export const GregoryHartmannTxData = [
  {
    txName: "Safe insurance Services",
    whatUsed: "Credit",
    debit: "+$800,000.00",
    date: " April 10, 2024",
    color: "green",
  },
  {
    txName: "Armor Texas Insurance Agency, Inc.",
    whatUsed: "Credit",
    debit: "+$250,000.00",
    date: "Feb 18, 2024",
    color: "green",
  },
  {
    txName: "Armor Texas Insurance Agency, Inc.",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Jan 20, 2024",
    color: "green",
  },
  {
    txName: "Mary Lou Roush Winings",
    whatUsed: "Credit",
    debit: "+$350,000.00",
    date: "Mar 21, 2023",
    color: "green",
  },
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jan 25, 2023",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 19, 2023",
    color: "green",
  },
  {
    txName: "Safe insurance Services",
    whatUsed: "Credit",
    debit: "+$270,000.00",
    date: "Jun 05, 2022",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "May 18, 2022",
    color: "red",
  },
  {
    txName: "Thumann Agency, Inc",
    whatUsed: "Credit",
    debit: "+$208,000.00",
    date: "May 05, 2022",
    color: "green",
  },
  {
    txName: "Tech Invest",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2021",
    color: "green",
  },
  {
    txName: "Safe insurance Services",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "Apr 25, 2021",
    color: "green",
  },
  {
    txName: "Anna Emily",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2021",
    color: "green",
  },
  {
    txName: "Williams Charles",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2020",
    color: "green",
  },
  {
    txName: "Walmart",
    whatUsed: "Debit",
    debit: "-$185.00",
    date: "Jan 1, 2020",
    color: "red",
  },
  {
    txName: "Power Ball Lottery",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Nov 15, 2019",
    color: "green",
  },
  {
    txName: "Texas Funding Corporation",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "July 2, 2019",
    color: "green",
  },
  {
    txName: "Mary Lou Roush Winings",
    whatUsed: "Credit",
    debit: "+$375,000.00",
    date: "Oct 21, 2015",
    color: "green",
  },
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "April 25, 2015",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jan 19, 2015",
    color: "green",
  },
];
export const DonnaAyooWilliamsTxData = [
  {
    txName: "Safe insurance Services",
    whatUsed: "Credit",
    debit: "+$800,000.00",
    date: " April 10, 2024",
    color: "green",
  },
  {
    txName: "Armor Texas Insurance Agency, Inc.",
    whatUsed: "Credit",
    debit: "+$250,000.00",
    date: "Feb 18, 2024",
    color: "green",
  },
  {
    txName: "Armor Texas Insurance Agency, Inc.",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Jan 20, 2024",
    color: "green",
  },
  {
    txName: "Mary Lou Roush Winings",
    whatUsed: "Credit",
    debit: "+$350,000.00",
    date: "Mar 21, 2023",
    color: "green",
  },
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jan 25, 2023",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 19, 2023",
    color: "green",
  },
  {
    txName: "Safe insurance Services",
    whatUsed: "Credit",
    debit: "+$270,000.00",
    date: "Jun 05, 2022",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "May 18, 2022",
    color: "red",
  },
  {
    txName: "Thumann Agency, Inc",
    whatUsed: "Credit",
    debit: "+$208,000.00",
    date: "May 05, 2022",
    color: "green",
  },
  {
    txName: "Tech Invest",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2021",
    color: "green",
  },
  {
    txName: "Safe insurance Services",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "Apr 25, 2021",
    color: "green",
  },
  {
    txName: "Anna Emily",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2021",
    color: "green",
  },
  {
    txName: "Williams Charles",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2020",
    color: "green",
  },
  {
    txName: "Walmart",
    whatUsed: "Debit",
    debit: "-$185.00",
    date: "Jan 1, 2020",
    color: "red",
  },
  {
    txName: "Power Ball Lottery",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Nov 15, 2019",
    color: "green",
  },
  {
    txName: "Texas Funding Corporation",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "July 2, 2019",
    color: "green",
  },
  {
    txName: "Mary Lou Roush Winings",
    whatUsed: "Credit",
    debit: "+$375,000.00",
    date: "Oct 21, 2015",
    color: "green",
  },
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "April 25, 2015",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jan 19, 2015",
    color: "green",
  },
];